# Generated by Django 2.0.2 on 2018-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucapp', '0005_auto_20180430_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hybridize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femaleParent', models.ManyToManyField(related_name='female', to='sucapp.SucInfo')),
                ('maleParent', models.ManyToManyField(related_name='male', to='sucapp.SucInfo')),
                ('progeny', models.ManyToManyField(related_name='progeny', to='sucapp.SucInfo')),
            ],
        ),
    ]
