# Generated by Django 2.0.2 on 2018-04-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hybapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hybridize',
            old_name='femaleParent',
            new_name='femaleparent',
        ),
        migrations.RenameField(
            model_name='hybridize',
            old_name='maleParent',
            new_name='maleparent',
        ),
    ]
