# Generated by Django 2.0.2 on 2018-04-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0006_auto_20180430_1710'),
        ('hybapp', '0002_auto_20180430_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybridize',
            name='progeny',
        ),
        migrations.AddField(
            model_name='hybridize',
            name='progeny',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progeny', to='sucapp.SucInfo'),
            preserve_default=False,
        ),
    ]
