# Generated by Django 2.0.2 on 2018-05-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0006_auto_20180430_1710'),
        ('hybapp', '0003_auto_20180430_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybridize',
            name='femaleparent',
        ),
        migrations.AddField(
            model_name='hybridize',
            name='femaleparent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='female', to='sucapp.SucInfo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='hybridize',
            name='maleparent',
        ),
        migrations.AddField(
            model_name='hybridize',
            name='maleparent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='male', to='sucapp.SucInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hybridize',
            name='progeny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progeny', to='sucapp.SucInfo'),
        ),
    ]
