# Generated by Django 2.0.2 on 2018-05-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hybapp', '0005_auto_20180502_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hybridize',
            options={'verbose_name': '杂交数据', 'verbose_name_plural': '杂交数据'},
        ),
    ]
