# Generated by Django 2.0.2 on 2018-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SucInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
                ('genus', models.CharField(max_length=20)),
                ('plantShape', models.CharField(max_length=8)),
                ('leafColor', models.CharField(max_length=8)),
                ('leafShape', models.CharField(max_length=10)),
                ('leafDent', models.CharField(max_length=4)),
                ('leafOpex', models.CharField(max_length=4)),
                ('lightTime', models.IntegerField(max_length=11)),
                ('water', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=16)),
                ('season', models.CharField(max_length=8)),
                ('introduction', models.TextField(max_length=20)),
            ],
        ),
    ]
