# Generated by Django 2.0.2 on 2018-04-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0005_auto_20180430_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucinfo',
            old_name='leafOpex',
            new_name='leafopex',
        ),
    ]
