# Generated by Django 2.0.2 on 2018-05-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0006_auto_20180430_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintain',
            options={'verbose_name': '养护知识', 'verbose_name_plural': '养护知识'},
        ),
        migrations.AlterModelOptions(
            name='sucinfo',
            options={'verbose_name': '多肉数据', 'verbose_name_plural': '多肉数据'},
        ),
    ]
