# Generated by Django 2.0.2 on 2018-05-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0007_auto_20180507_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucinfo',
            name='femaleparent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucfemale', to='sucapp.SucInfo'),
        ),
        migrations.AddField(
            model_name='sucinfo',
            name='maleparent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucmale', to='sucapp.SucInfo'),
        ),
    ]
