# Generated by Django 2.0.2 on 2018-05-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0008_auto_20180530_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='familygenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=20)),
                ('genus', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '科属表',
                'verbose_name_plural': '科属表',
            },
        ),
        migrations.AlterField(
            model_name='sucinfo',
            name='femaleparent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucfemale', to='sucapp.SucInfo'),
        ),
        migrations.AlterField(
            model_name='sucinfo',
            name='maleparent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucmale', to='sucapp.SucInfo'),
        ),
    ]
