# Generated by Django 2.0.2 on 2018-05-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0009_auto_20180531_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucinfo',
            name='femaleparent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucfemale', to='sucapp.SucInfo'),
        ),
        migrations.AlterField(
            model_name='sucinfo',
            name='maleparent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucmale', to='sucapp.SucInfo'),
        ),
    ]
