# Generated by Django 2.0.2 on 2018-05-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0010_auto_20180531_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='familygenus',
        ),
    ]
