# Generated by Django 2.0.2 on 2018-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucapp', '0011_delete_familygenus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=20)),
                ('genus', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '科属表',
                'verbose_name_plural': '科属表',
            },
        ),
    ]
